development:
  adapter: postgresql
  database: ppapi_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: ppapi_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ppapi_production
  pool: 5
  timeout: 5000